### ISSUE TITLE
Reason behind commented test

### ISSUE THREAD

**Issue by RauppRafael** [islishude/uniswapv2-solc0.8#12]
Hi @islishude, 

I have also updated Uniswap v2 to Solidity 0.8. While running tests, I noticed a particular test case was failing and started searching for fixes and found that you commented it out, and I'm encountering an exception on the same line in my implementation.

The original test seems to fail in my context, and it appears this may be due to the Solidity version upgrade.

My questions are as follows:

1. Was this test originally commented out due to a similar issue?
2. If so, is this failure specific to the Solidity version change, or is there a larger underlying issue at play?
3. Based on your experience, do you anticipate that this could potentially affect other aspects of the exchange behavior?

I'm trying to ensure a smooth upgrade and maintain the integrity of the codebase, so your insights on this matter would be incredibly valuable. Additionally, this discussion could potentially unveil improvements beneficial to both our implementations.

Thank you for your time and support.

https://github.com/islishude/uniswapv2-solc0.8/blob/2024e4e64bc8af34920afbfee9c7aa7d63b3f4c0/src/test/UniswapV2Pair.spec.ts#L366

**Comment by RauppRafael** [comment]
Update: 

I've just downloaded and tested the original Uniswap v2 repo and found out that `price0CumulativeLast` and `price1CumulativeLast` are equal to `0x010000000000000000000000000000` in their contracts, but in our contracts it results in `0x020000000000000000000000000000`

**Comment by islishude** [comment]
Thanks for the report. I have removed the comment.
