### ISSUE TITLE
Stability?

### ISSUE THREAD

**Issue by 0xrebased** [islishude/uniswapv2-solc0.8#3]
Hey @islishude, is this fork stable (enough)?

- Bera Dev

**Comment by islishude** [comment]
yep, all test cases have been paased, you can check with upstream repository

**Comment by islishude** [comment]
if you have any questions, feel free to open this again

**Comment by 0xrebased** [comment]
awesome thanks @islishude, have you looked into doing the v2-periphery as well? I can assist if you are interested.

**Comment by islishude** [comment]
Thanks, PR is welcome
