### ISSUE TITLE
0.8 Cannot Overflow

### ISSUE THREAD

**Issue by 0xrebased** [islishude/uniswapv2-solc0.8#4]
Given enough calls to `_update` the contract will end up in an unrecoverable state due 0.8's revert on overflow.

![Uploading image.png…]()

**Comment by 0xrebased** [comment]
![image](https://user-images.githubusercontent.com/93690142/146059845-86313b44-fa51-455c-a97c-7efcd0f0fb4a.png)

**Comment by 0xrebased** [comment]
(UniswapV2Pair.sol)

**Comment by 0xrebased** [comment]
or is it referring to overflowing a uint112? I still think after enough time, the contract ends up in an unrecoverable state.

**Comment by 0xrebased** [comment]
Fixed https://github.com/islishude/uniswapv2-solc0.8/pull/5

**Comment by islishude** [comment]
I don't think this is a must change, because if this issue is triggered, it will be decades later

**Comment by islishude** [comment]
Has Merged.
